### ISSUE TITLE
license-tool-plugin 1.0.2 fails to follow redirect to default approved licenses URL

### ISSUE THREAD

**Issue by krumts** [eclipse-dash/dash-licenses#374]
In the Memory Analyzer project we started getting errors like this one, when building the MAT project with maven / tycho.

```
[ERROR] Failed to execute goal org.eclipse.dash:license-tool-plugin:1.0.2:license-check (license-check) on project parent: 
Execution license-check of goal org.eclipse.dash:license-tool-plugin:1.0.2:license-check failed: 
Cannot invoke "java.util.Map.keySet()" because "this.approvedLicenses" is null -> [Help 1]
```

In our pom.xml we didn't explicitly configure the approved licenses URL, and were thus using the default "https://www.eclipse.org/legal/licenses.json". Looks like this one was moved one level deeper, under /legal/licenses/licenses.json and the plugin didn't build correctly, although the old URL sends a 302 response to redirect to the new location.

I haven't looked deeper into this. Adding the new URL explicitly resolved the issue for us. 
I thought it would be good to report the issue.

Just for reference, this is the issue on the MAT project https://github.com/eclipse-mat/mat/issues/64.

**Comment by pzygielo** [comment]
Seems to work fine in current 1.1.0.

**Comment by krumts** [comment]
Indeed, it works. I did check for new versions in the repository before opening the ticket and saw the 1.0.3-snapshot, but I have overlooked that there is a 1.1.0 available. Thanks for the help and sorry to bother you with a fixed issue!

**Comment by krumts** [comment]
closing the issue, as it was already fixed

**Comment by waynebeaton** [comment]
We changed the HTTP client configuration to support redirects.

I've also updated the default URL in the code.
